== Redoculous Server - "Skip the build!"

Redoculous is a simple Markup language preview and publishing server - edit 
documents locally in real-time, and publish instantly to the web
with a few small snippits of HTML. Designed for handling multiple
versions of documents, publishing directly from source has never 
been easier. Just use a little basic HTML to add a Redoculous pane
to any web page, and include the required scripts to publish
your documentation instantly.

[source,html]
.Using Redoculous.js and a DIV element:
----
<!DOCTYPE html>
<html>
<head>
<title>Redoculous Example</title>
<meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="css/asciidoctor.css">
<script src="js/jquery.min.js"></script>
<script src="js/jquery.history.js"></script>
<script src="js/redoculous.js"></script>
</head>
<body>
	<div 
	    data-redoculous="http://localhost:8080/redoculous"
		data-repo="https://github.com/ocpsoft/redoculous.git"
		data-ref="master"
		data-repo-root="/docs" 
		data-root="/redoculous/docs">
	</div>
</body>
</html>
----

== Configuration attributes

NOTE: All configuration attributes are required unless otherwise specified.

data-redoculous:: Creates a content pane where selected documents will be rendered
and specifies the URL of the Redoculous server that will handle document requests.
This pane will inherit all CSS and styles from the page in which it resides, just
like a normal HTML element.
+
--
For example, if your Redoculous server is located at http://redoculous.io/, you would 
use the following +data-redoculous+ configuration:
[source,html]
----
<div data-redoculous="http://redoculous.io" ... >
----
However, if you are running a local server, on port 8080 under the context-root 
+/redoculous+, then you would use the following configuration:
[source,html]
----
<div data-redoculous="http://localhost:8080/redoculous" ... >
----
--
data-repo:: Specifies the git repository URL from which this pane will display rendered
documents.
+
For example, if your un-rendered documents are hosted on link:http://github.com/[GitHub],
then you would use the HTTPS repository URL in your +data-repo+ configuration.
+
[source,html]
----
<div ... data-repo="https://github.com/ocpsoft/redoculous.git" ... >
----

data-ref:: Specifies the git ref from which this pane will display rendered documents.
+
For example, if your wish to display documents from a specific release tag, say +2.0.0.Final+,
then you would simply set the tag name in your +data-ref+ configuration.
+
[source,html]
----
<div ... data-ref="2.0.0.Final" ... >
----

data-repo-root:: Specifies the root path of the git repository from which to display rendered documents.
+
For example, if your wish to display documents from a sub-folder in the configured repo, you
would set the sub-folder path in your +data-repo-root+ configuration.
+
[source,html]
----
<div ... data-ref="2.0.0.Final" ... >
----

data-root:: Specifies the root URL from which documents may be accessed on the server.
+
For example, if you host your documents at the root URL http://ocpsoft.org/project/docs/,
you would set the absolute path to the documents root page in your +data-root+ configuration,
making sure to use the full path -- excluding query-parameters. 
+
[source,html]
----
<div ... data-root="/project/docs/" ... >
----

data-onload:: Specifies a fragment of JavaScript to execute after each document has
loaded.
+
For example, if you wish to call a JavaScript function after displaying each document,
simply pass the function you wish to call in the +data-onload+ configuration. 
+
[source,html]
----
<div ... data-onload="alert('Document loaded!');" ... >
----

That's it! You should now see your documents rendered in place of the +data-redoculous+
 element.
 
== Support
If you are having difficulty with Redoculous, please visit http://ocpsoft.org/support/redoculous-users/
and post a question. We will respond as quickly as possible.
 
== Get involved
To learn more and get involved, visit the project homepage at http://ocpsoft.org/redoculous/,
also, get the source-code at http://github.com/ocpsoft/redoculous




